-- 13 — Prepared statements and generic/custom plan investigation
-- PostgreSQL session-local lab. Run in a disposable database.
--
-- Goal:
-- 1. Separate SQL structure from values.
-- 2. Inspect prepared-statement behavior.
-- 3. Understand why data distribution can make a custom plan better
--    for one parameter and a generic plan better for another workload.

DROP TABLE IF EXISTS plan_cache_lab;
CREATE TABLE plan_cache_lab (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tenant_id integer NOT NULL,
  payload text NOT NULL
);

INSERT INTO plan_cache_lab (tenant_id, payload)
SELECT 1, 'large tenant row'
FROM generate_series(1, 90000);

INSERT INTO plan_cache_lab (tenant_id, payload)
SELECT 2, 'small tenant row'
FROM generate_series(1, 1000);

CREATE INDEX plan_cache_lab_tenant_idx ON plan_cache_lab(tenant_id);
ANALYZE plan_cache_lab;

PREPARE tenant_lookup(integer) AS
SELECT count(*)
FROM plan_cache_lab
WHERE tenant_id = $1;

-- Inspect a concrete execution with a supplied value.
EXPLAIN (ANALYZE, BUFFERS)
EXECUTE tenant_lookup(2);

-- Compare another parameter value. Data distribution matters.
EXPLAIN (ANALYZE, BUFFERS)
EXECUTE tenant_lookup(1);

-- PostgreSQL may choose generic/custom planning for prepared statements.
-- Inspect the server setting that controls the preference.
SHOW plan_cache_mode;

-- Inspect prepared statements and how often PostgreSQL selected each plan type.
SELECT name, parameter_types, generic_plans, custom_plans
FROM pg_prepared_statements
WHERE name = 'tenant_lookup';

-- Force custom planning for an experiment.
SET LOCAL plan_cache_mode = 'force_custom_plan';
EXPLAIN (ANALYZE, BUFFERS) EXECUTE tenant_lookup(2);

-- Force generic planning for an experiment.
SET LOCAL plan_cache_mode = 'force_generic_plan';
EXPLAIN (ANALYZE, BUFFERS) EXECUTE tenant_lookup(2);

DEALLOCATE tenant_lookup;

-- Production questions:
-- * Is the parameter distribution highly skewed?
-- * Is the plan stable across representative values?
-- * Does forcing a custom/generic plan materially change latency?
-- * Is the prepared statement generated by the application/ORM?
-- * Was the comparison made with representative data and warm/cold cache
--   conditions appropriate to the workload?
