"use client";
import {useMemo,useState} from "react";
import {BookOpen,Database,Mail,Search,ShieldCheck,Terminal,CheckCircle2,ArrowRight} from "lucide-react";

const lessons=[
 {id:"01",level:"Beginner",title:"Database foundations",desc:"Tables, rows, keys, schemas, NULL and relational thinking."},
 {id:"02",level:"Beginner",title:"SELECT mastery",desc:"Filtering, sorting, aliases, expressions and pagination."},
 {id:"03",level:"Intermediate",title:"Joins & aggregation",desc:"INNER/LEFT joins, GROUP BY, HAVING and conditional aggregates."},
 {id:"04",level:"Intermediate",title:"Subqueries & CASE",desc:"Correlated subqueries, EXISTS, CASE and business rules."},
 {id:"05",level:"Advanced",title:"CTEs & windows",desc:"Readable pipelines, recursive CTEs and ranking analytics."},
 {id:"06",level:"Advanced",title:"Transactions",desc:"ACID, isolation, locks, rollback and concurrency."},
 {id:"07",level:"Expert",title:"JSONB & PostgreSQL",desc:"Semi-structured data, operators, indexing and query design."},
 {id:"08",level:"Expert",title:"Partitioning & RLS",desc:"Large tables, pruning, row-level security and operational design."},
 {id:"09",level:"Data Engineering",title:"Cohorts & incremental loads",desc:"Data quality, retention, watermarks and analytics."},
 {id:"10",level:"Real World",title:"Banking project",desc:"Schema, seed data, transfers, reports, security and troubleshooting."}
];

export default function Home(){
 const [user,setUser]=useState<string|null>(typeof window!=="undefined"?localStorage.getItem("sql_user"):null);
 const [email,setEmail]=useState(""); const [search,setSearch]=useState(""); const [done,setDone]=useState<string[]>(typeof window!=="undefined"?JSON.parse(localStorage.getItem("sql_done")||"[]"):[]);
 const filtered=useMemo(()=>lessons.filter(x=>(x.title+" "+x.desc+" "+x.level).toLowerCase().includes(search.toLowerCase())),[search]);
 const login=()=>{if(!email.includes("@"))return;localStorage.setItem("sql_user",email);setUser(email);localStorage.setItem("sql_welcome_email","queued");};
 const toggle=(id:string)=>{const next=done.includes(id)?done.filter(x=>x!==id):[...done,id];setDone(next);localStorage.setItem("sql_done",JSON.stringify(next));};
 if(!user)return <main className="shell"><div className="container"><nav className="nav"><div className="brand">SQL<span>Lab</span></div><div className="pill">Open source learning</div></nav><section className="hero"><div className="eyebrow">From zero → production</div><h1>Learn SQL by <span className="green">building</span>.</h1><p className="sub">A structured PostgreSQL journey with theory, runnable queries, practice challenges, real-world projects and production engineering.</p></section><div className="card" style={{maxWidth:520,margin:"20px auto 80px"}}><h2>Start your learning journey</h2><p className="muted">Local demo login. Your progress stays in this browser.</p><input className="input" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/><button className="btn primary" style={{width:"100%",marginTop:12}} onClick={login}>Enter SQL Lab <ArrowRight size={16}/></button><p className="muted" style={{fontSize:12,marginTop:14}}>Email delivery is optional and disabled by default. No password is stored.</p></div></div></main>;
 return <main className="shell"><div className="container"><nav className="nav"><div className="brand">SQL<span>Lab</span></div><div className="row"><span className="pill">{user}</span><button className="btn" onClick={()=>{localStorage.removeItem("sql_user");setUser(null)}}>Sign out</button></div></nav><section className="hero"><div className="eyebrow">Your SQL workspace</div><h1>Build database <span className="green">confidence</span>.</h1><p className="sub">Theory first. Query next. Practice until it becomes production skill.</p><div className="grid two"><div className="card"><div className="between"><div><div className="muted">Progress</div><strong>{done.length} / {lessons.length} lessons</strong></div><Database className="green"/></div><div className="progress" style={{marginTop:14}}><i style={{width:(done.length/lessons.length*100)+"%"}}/></div></div><div className="card"><div className="muted">Welcome</div><h3>You're in. 🎓</h3><p className="muted">A welcome-email event was queued locally. Connect Resend to send a real email.</p><div className="row"><Mail size={16}/><span className="pill">local demo</span></div></div></div></section><section className="card"><div className="between"><div><h2>Curriculum</h2><p className="muted">Theory → example → practice → challenge</p></div><div className="row"><Search size={17}/><input className="input" style={{width:240}} placeholder="Search lessons" value={search} onChange={e=>setSearch(e.target.value)}/></div></div>{filtered.map(l=><div className="lesson" key={l.id}><div className="pill">{l.level}</div><div style={{flex:1}}><div className="between"><div><strong>{l.title}</strong><div className="muted">{l.desc}</div></div><button className="btn" onClick={()=>toggle(l.id)}>{done.includes(l.id)?<CheckCircle2 size={16}/>:<BookOpen size={16}/>}</button></div></div></div>)}</section><section className="grid" style={{margin:"20px 0 60px"}}><div className="card"><Terminal className="green"/><h3>Runnable SQL</h3><p className="muted">PostgreSQL scripts you can copy, execute and modify.</p></div><div className="card"><ShieldCheck className="green"/><h3>Production thinking</h3><p className="muted">Indexes, locks, security, RCA and performance tuning.</p></div><div className="card"><BookOpen className="green"/><h3>Open learning</h3><p className="muted">Contribute lessons, challenges, fixes and project ideas.</p></div></section></div></main>
}
